name: funnel
favicon: null
layout_spectrum: 0.16173
typography_spectrum: 0.74915
title: Marketing Funnel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c6c6c6'
    - '#f6f6f6'
    - '#393742'
    - '#0d0c11'
    - '#7e7d83'
  brandStrength: 0
  lightness: 0.5233232071623206
  saturation: 0.6798293269239366
  rhythmicContrast: 0.10914354328997433
purpose: []
