name: funnel
favicon: null
layout_spectrum: 0.16173
typography_spectrum: 0.74915
title: Marketing Funnel
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9ccc3c'
    - '#53585b'
    - '#babcbe'
    - '#7d8082'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
